### ISSUE TITLE
Suggestion: Add support for customer, yourref, yourmail like in scrlttr2 / LaTeX

### ISSUE THREAD

**Issue by moritz1000** [pascal-huber/typst-letter-template#2]
Hello,

so far I have been using this [Latex-Briefvorlage nach DIN 5008](https://github.com/PanCakeConnaisseur/latex-briefvorlage-din-5008) letter template.

It offers [this options](https://github.com/PanCakeConnaisseur/latex-briefvorlage-din-5008#briefvorlage-mit-allen-optionen):
![image](https://github.com/dvdvgt/typst-letter/assets/35174351/e875e782-ed9a-4938-ac57-6f0da633b6c2)
e.g.:
```
% Kundennummer
%\setkomavar{customer}[\customername]{DE-112233}

% Ihr Zeichen
%\setkomavar{yourref}[\yourrefname]{IZ-12345}

% Ihr Schreiben vom
%\setkomavar{yourmail}[\yourmailname]{1. April 2018}
```
in LaTeX.

___

Would it be possible to also add something like this to this awesome typst letter template?

Kind regards.

**Comment by pascal-huber** [comment]
Hi,

Thanks for the kind words!

Indeed I have a temporary state of this project with such a table. I just pushed it onto the [next](https://github.com/pascal-huber/typst-letter-template/tree/next) branch with:

```
    horizontal_table: (
        "Ihr Zeichen": "Bananalover149",
        "Ihre Nachricht vom": "12.12.2022",
        "Unser Zeichen": "BananaFactory",
        "Datum": "06.08.2023",
    ),
```

~~I'm not quite sure yet about the spacing of it as it seems a bit far down but moving it up would violate the DIN norm.~~ (was a bug)

**Comment by pascal-huber** [comment]
Merged. Feel free to reopen if you wish to discuss this further.

**Comment by moritz1000** [comment]
Thank you! :)

**Comment by moritz1000** [comment]
Thank you, it looks fantastic!
